# Generated by Django 4.2.30 on 2026-09-16 17:52

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospitals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_type', models.CharField(choices=[('HEART', 'Heart'), ('LIVER', 'Liver'), ('KIDNEY', 'Kidney'), ('LUNG', 'Lung'), ('PANCREAS', 'Pancreas'), ('CORNEA', 'Cornea')], max_length=20)),
                ('status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESERVED', 'Reserved'), ('IN_TRANSIT', 'In transit'), ('DELIVERED', 'Delivered'), ('EXPIRED', 'Expired')], default='AVAILABLE', max_length=20)),
                ('donor_reference', models.CharField(max_length=100, unique=True)),
                ('available_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('expires_at', models.DateTimeField()),
                ('hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organs', to='hospitals.hospital')),
            ],
        ),
        migrations.CreateModel(
            name='OrganRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('organ_type', models.CharField(choices=[('HEART', 'Heart'), ('LIVER', 'Liver'), ('KIDNEY', 'Kidney'), ('LUNG', 'Lung'), ('PANCREAS', 'Pancreas'), ('CORNEA', 'Cornea')], max_length=20)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], max_length=10)),
                ('required_by', models.DateTimeField(validators=[django.core.validators.MinValueValidator(django.utils.timezone.now)])),
                ('status', models.CharField(choices=[('OPEN', 'Open'), ('MATCHED', 'Matched'), ('ACCEPTED', 'Accepted'), ('IN_DELIVERY', 'In delivery'), ('COMPLETED', 'Completed'), ('CANCELLED', 'Cancelled')], default='OPEN', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('accepted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='accepted_requests', to='hospitals.hospital')),
                ('matched_organ', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='matched_requests', to='organs.organ')),
                ('requesting_hospital', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='organ_requests', to='hospitals.hospital')),
            ],
        ),
        migrations.AddConstraint(
            model_name='organrequest',
            constraint=models.CheckConstraint(check=models.Q(('requesting_hospital', models.F('accepted_by')), _negated=True), name='requesting_and_accepting_hospital_differ'),
        ),
        migrations.AddConstraint(
            model_name='organ',
            constraint=models.CheckConstraint(check=models.Q(('expires_at__gt', models.F('available_at'))), name='organ_expiry_after_available'),
        ),
    ]
